general.live_config_reload = true

# Font
[font]
# size = 16.0
size = 10

# alacritty.toml

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 1
# decorations = "full"
padding = { x = 0, y = 0 }

[colors.primary]
foreground = "#f0f0f0"
background = "#111111"
# [colors.primary]
# background = "#000000"  # dark0_hard
# foreground = "#ebdbb2"  # light1
#
